In [55]:
# Import BeautifulSoup for reading and parsing HTML
from bs4 import BeautifulSoup
# Import requests to send HTTP requests to the website
import requests

In [56]:
# Website link that we want to scrape
url = 'https://en.wikipedia.org/wiki/List_of_largest_companies_in_the_Philippines'

In [57]:
# Send a request to the website
page = requests.get(url)
# Add headers to make the request look like it came from a real browser
# Some websites block requests without a user-agent
headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/115.0'
    # you can change it if you want to
}
# Send another request with headers included
page = requests.get(url, headers=headers)
# Convert the website content into a BeautifulSoup object
# This allows us to search and extract HTML elements easily
soup = BeautifulSoup(page.content, 'html')

In [58]:
# Print the entire HTML structure of the page
# Useful for checking the website structure while scraping
print(soup.prettify())

<!DOCTYPE html>
<html class="client-nojs vector-feature-language-in-header-enabled vector-feature-language-in-main-menu-disabled vector-feature-language-in-main-page-header-disabled vector-feature-page-tools-pinned-disabled vector-feature-toc-pinned-clientpref-1 vector-feature-main-menu-pinned-disabled vector-feature-limited-width-clientpref-1 vector-feature-limited-width-content-enabled vector-feature-custom-font-size-clientpref-1 vector-feature-appearance-pinned-clientpref-1 skin-theme-clientpref-day vector-sticky-header-enabled vector-toc-available skin-theme-clientpref-thumb-standard" dir="ltr" lang="en">
 <head>
  <meta charset="utf-8"/>
  <title>
   List of largest companies in the Philippines - Wikipedia
  </title>
  <script>
   (function(){var className="client-js vector-feature-language-in-header-enabled vector-feature-language-in-main-menu-disabled vector-feature-language-in-main-page-header-disabled vector-feature-page-tools-pinned-disabled vector-feature-toc-pinned-clientpref-1 vector-feature-main-menu-pinned-disabled vector-feature-limited-width-clientpref-1 vector-feature-limited-width-content-enabled vector-feature-custom-font-size-clientpref-1 vector-feature-appearance-pinned-clientpref-1 skin-theme-clientpref-day vector-sticky-header-enabled vector-toc-available skin-theme-clientpref-thumb-standard";var cookie=document.cookie.match(/(?:^|; )enwikimwclientpreferences=([^;]+)/);if(cookie){cookie[1].split('%2C').forEach(function(pref){className=className.replace(new RegExp('(^| )'+pref.replace(/-clientpref-\w+$|[^\w-]+/g,'')+'-clientpref-\\w+( |$)'),'$1'+pref+'$2');});}document.documentElement.className=className;}());RLCONF={"wgBreakFrames":false,"wgSeparatorTransformTable":["",""],"wgDigitTransformTable":["",""],"wgDefaultDateFormat":"dmy","wgMonthNames":["","January","February","March","April","May","June","July","August","September","October","November","December"],"wgRequestId":"0e2e02d3-1afd-4c72-a0af-c2273425d35d","wgCanonicalNamespace":"","wgCanonicalSpecialPageName":false,"wgNamespaceNumber":0,"wgPageName":"List_of_largest_companies_in_the_Philippines","wgTitle":"List of largest companies in the Philippines","wgCurRevisionId":1323855775,"wgRevisionId":1323855775,"wgArticleId":77677025,"wgIsArticle":true,"wgIsRedirect":false,"wgAction":"view","wgUserName":null,"wgUserGroups":["*"],"wgCategories":["Articles with short description","Short description is different from Wikidata","Lists of largest private companies by country","Lists of companies of the Philippines"],"wgPageViewLanguage":"en","wgPageContentLanguage":"en","wgPageContentModel":"wikitext","wgRelevantPageName":"List_of_largest_companies_in_the_Philippines","wgRelevantArticleId":77677025,"wgTempUserName":null,"wgIsProbablyEditable":true,"wgRelevantPageIsProbablyEditable":true,"wgRestrictionEdit":[],"wgRestrictionMove":[],"wgNoticeProject":"wikipedia","wgFlaggedRevsParams":{"tags":{"status":{"levels":1}}},"wgConfirmEditCaptchaNeededForGenericEdit":"hcaptcha","wgConfirmEditForceShowCaptcha":false,"wgConfirmEditHCaptchaVisualEditorOnLoadIntegrationEnabled":false,"wgConfirmEditHCaptchaSiteKey":"5d0c670e-a5f4-4258-ad16-1f42792c9c62","wgMediaViewerOnClick":true,"wgMediaViewerEnabledByDefault":true,"wgPopupsFlags":0,"wgVisualEditor":{"pageLanguageCode":"en","pageLanguageDir":"ltr","pageVariantFallbacks":"en"},"wgMFDisplayWikibaseDescriptions":{"search":true,"watchlist":true,"tagline":false,"nearby":true},"wgWMESchemaEditAttemptStepOversample":false,"wgWMEPageLength":8000,"wgTestKitchenUserExperiments":{"overrides":[],"enrolled":[],"assigned":[],"subject_ids":[]},"wgEditSubmitButtonLabelPublish":true,"wgVisualEditorPageIsDisambiguation":false,"wgULSPosition":"interlanguage","wgULSisCompactLinksEnabled":false,"wgVector2022LanguageInHeader":true,"wgULSisLanguageSelectorEmpty":false,"wgULSLanguageSelectorV2Enabled":false,"wgWikibaseItemId":"Q130235855","wgCheckUserClientHintsHeadersJsApi":["brands","architecture","bitness","fullVersionList","mobile","model","platform","platformVersion"],"GEHomepageSuggestedEditsEnableTopics":true,"wgGESuggestedEditsTaskTypes":{"taskTypes":["copyedit","link-recommendation"],"unavailableTaskTypes":[]},"wgGETopicsMatchModeEnabled":false,"wgGELevelingUpEnabledForUser":false,"wgPersonalDashboardMenuVisible":false};
RLSTATE={"ext.globalCssJs.user.styles":"ready","site.styles":"ready","user.styles":"ready","ext.globalCssJs.user":"ready","user":"ready","user.options":"loading","ext.wikimediamessages.styles":"ready","ext.cite.styles":"ready","skins.vector.search.codex.styles":"ready","skins.vector.styles":"ready","skins.vector.icons":"ready","jquery.tablesorter.styles":"ready","ext.visualEditor.desktopArticleTarget.noscript":"ready","ext.uls.interlanguage":"ready","wikibase.client.init":"ready"};RLPAGEMODULES=["ext.parsermigration.survey","ext.cite.ux-enhancements","site","mediawiki.page.ready","jquery.tablesorter","mediawiki.toc","skins.vector.js","ext.centralNotice.geoIP","ext.centralNotice.startUp","ext.gadget.ReferenceTooltips","ext.gadget.switcher","ext.urlShortener.toolbar","ext.centralauth.centralautologin","ext.testKitchen","mmv.bootstrap","ext.popups","ext.visualEditor.desktopArticleTarget.init","ext.echo.centralauth","ext.eventLogging","ext.wikimediaEvents","ext.navigationTiming","ext.uls.interface","ext.cx.eventlogging.campaigns","ext.cx.uls.quick.actions","wikibase.client.vector-2022","wikibase.databox.fromWikidata","ext.checkUser.clientHints","ext.quicksurveys.init","ext.growthExperiments.SuggestedEditSession"];
  </script>
  <script>
   (RLQ=window.RLQ||[]).push(function(){mw.loader.impl(function(){return["user.options@12s5i",function($,jQuery,require,module){mw.user.tokens.set({"patrolToken":"+\\","watchToken":"+\\","csrfToken":"+\\"});
}];});});
  </script>
  <link href="/w/load.php?lang=en&amp;modules=ext.cite.styles%7Cext.uls.interlanguage%7Cext.visualEditor.desktopArticleTarget.noscript%7Cext.wikimediamessages.styles%7Cjquery.tablesorter.styles%7Cskins.vector.icons%2Cstyles%7Cskins.vector.search.codex.styles%7Cwikibase.client.init&amp;only=styles&amp;skin=vector-2022" rel="stylesheet"/>
  <script async="" src="/w/load.php?lang=en&amp;modules=startup&amp;only=scripts&amp;raw=1&amp;skin=vector-2022">
  </script>
  <meta content="" name="ResourceLoaderDynamicStyles"/>
  <link href="/w/load.php?lang=en&amp;modules=site.styles&amp;only=styles&amp;skin=vector-2022" rel="stylesheet"/>
  <meta content="MediaWiki 1.47.0-wmf.1" name="generator"/>
  <meta content="origin" name="referrer"/>
  <meta content="origin-when-cross-origin" name="referrer"/>
  <meta content="max-image-preview:standard" name="robots"/>
  <meta content="telephone=no" name="format-detection"/>
  <meta content="width=1120" name="viewport"/>
  <meta content="List of largest companies in the Philippines - Wikipedia" property="og:title"/>
  <meta content="website" property="og:type"/>
  <link href="/w/index.php?title=List_of_largest_companies_in_the_Philippines&amp;action=edit" rel="alternate" title="Edit this page" type="application/x-wiki"/>
  <link href="/static/apple-touch/wikipedia.png" rel="apple-touch-icon"/>
  <link href="/static/favicon/wikipedia.ico" rel="icon"/>
  <link href="/w/rest.php/v1/search" rel="search" title="Wikipedia (en)" type="application/opensearchdescription+xml"/>
  <link href="//en.wikipedia.org/w/api.php?action=rsd" rel="EditURI" type="application/rsd+xml"/>
  <link href="https://en.wikipedia.org/wiki/List_of_largest_companies_in_the_Philippines" rel="canonical"/>
  <link href="https://creativecommons.org/licenses/by-sa/4.0/deed.en" rel="license"/>
  <link href="/w/index.php?title=Special:RecentChanges&amp;feed=atom" rel="alternate" title="Wikipedia Atom feed" type="application/atom+xml"/>
  <link href="//meta.wikimedia.org" rel="dns-prefetch">
   <link href="auth.wikimedia.org" rel="dns-prefetch"/>
  </link>
 </head>
 <body class="skin--responsive skin-vector skin-vector-search-vue mediawiki ltr sitedir-ltr mw-hide-empty-elt ns-0 ns-subject mw-editable page-List_of_largest_companies_in_the_Philippines rootpage-List_of_largest_companies_in_the_Philippines skin-vector-2022 action-view">
  <div aria-live="polite" class="mw-aria-live-region" id="mw-aria-live-region">
  </div>
  <a class="mw-jump-link" href="#bodyContent">
   Jump to content
  </a>
  <div class="vector-header-container">
   <header class="vector-header mw-header no-font-mode-scale">
    <div class="vector-header-start">
     <nav aria-label="Site" class="vector-main-menu-landmark">
      <div class="vector-dropdown vector-main-menu-dropdown vector-button-flush-left vector-button-flush-right" id="vector-main-menu-dropdown" title="Main menu">
       <input aria-haspopup="true" aria-label="Main menu" class="vector-dropdown-checkbox" data-event-name="ui.dropdown-vector-main-menu-dropdown" id="vector-main-menu-dropdown-checkbox" role="button" type="checkbox"/>
       <label aria-hidden="true" class="vector-dropdown-label cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only" for="vector-main-menu-dropdown-checkbox" id="vector-main-menu-dropdown-label">
        <span class="vector-icon mw-ui-icon-menu mw-ui-icon-wikimedia-menu">
        </span>
        <span class="vector-dropdown-label-text">
         Main menu
        </span>
       </label>
       <div class="vector-dropdown-content">
        <div class="vector-unpinned-container" id="vector-main-menu-unpinned-container">
         <div class="vector-main-menu vector-pinnable-element" id="vector-main-menu">
          <div class="vector-pinnable-header vector-main-menu-pinnable-header vector-pinnable-header-unpinned" data-feature-name="main-menu-pinned" data-pinnable-element-id="vector-main-menu" data-pinned-container-id="vector-main-menu-pinned-container" data-unpinned-container-id="vector-main-menu-unpinned-container">
           <div class="vector-pinnable-header-label">
            Main menu
           </div>
           <button class="vector-pinnable-header-toggle-button vector-pinnable-header-pin-button" data-event-name="pinnable-header.vector-main-menu.pin">
            move to sidebar
           </button>
           <button class="vector-pinnable-header-toggle-button vector-pinnable-header-unpin-button" data-event-name="pinnable-header.vector-main-menu.unpin">
            hide
           </button>
          </div>
          <div class="vector-menu mw-portlet mw-portlet-navigation" id="p-navigation">
           <div class="vector-menu-heading">
            Navigation
           </div>
           <div class="vector-menu-content">
            <ul class="vector-menu-content-list">
             <li class="mw-list-item" id="n-mainpage-description">
              <a accesskey="z" href="/wiki/Main_Page" title="Visit the main page [z]">
               <span>
                Main page
               </span>
              </a>
             </li>
             <li class="mw-list-item" id="n-contents">
              <a href="/wiki/Wikipedia:Contents" title="Guides to browsing Wikipedia">
               <span>
                Contents
               </span>
              </a>
             </li>
             <li class="mw-list-item" id="n-currentevents">
              <a href="/wiki/Portal:Current_events" title="Articles related to current events">
               <span>
                Current events
               </span>
              </a>
             </li>
             <li class="mw-list-item" id="n-randompage">
              <a accesskey="x" href="/wiki/Special:Random" title="Visit a randomly selected article [x]">
               <span>
                Random article
               </span>
              </a>
             </li>
             <li class="mw-list-item" id="n-aboutsite">
              <a href="/wiki/Wikipedia:About" title="Learn about Wikipedia and how it works">
               <span>
                About Wikipedia
               </span>
              </a>
             </li>
             <li class="mw-list-item" id="n-contactpage">
              <a href="//en.wikipedia.org/wiki/Wikipedia:Contact_us" title="How to contact Wikipedia">
               <span>
                Contact us
               </span>
              </a>
             </li>
            </ul>
           </div>
          </div>
          <div class="vector-menu mw-portlet mw-portlet-interaction" id="p-interaction">
           <div class="vector-menu-heading">
            Contribute
           </div>
           <div class="vector-menu-content">
            <ul class="vector-menu-content-list">
             <li class="mw-list-item" id="n-help">
              <a href="/wiki/Help:Contents" title="Guidance on how to use and edit Wikipedia">
               <span>
                Help
               </span>
              </a>
             </li>
             <li class="mw-list-item" id="n-introduction">
              <a href="/wiki/Help:Introduction" title="Learn how to edit Wikipedia">
               <span>
                Learn to edit
               </span>
              </a>
             </li>
             <li class="mw-list-item" id="n-portal">
              <a href="/wiki/Wikipedia:Community_portal" title="The hub for editors">
               <span>
                Community portal
               </span>
              </a>
             </li>
             <li class="mw-list-item" id="n-recentchanges">
              <a accesskey="r" href="/wiki/Special:RecentChanges" title="A list of recent changes to Wikipedia [r]">
               <span>
                Recent changes
               </span>
              </a>
             </li>
             <li class="mw-list-item" id="n-upload">
              <a href="/wiki/Wikipedia:File_upload_wizard" title="Add images or other media for use on Wikipedia">
               <span>
                Upload file
               </span>
              </a>
             </li>
             <li class="mw-list-item" id="n-specialpages">
              <a accesskey="q" href="/wiki/Special:SpecialPages" title="A list of all special pages [q]">
               <span>
                Special pages
               </span>
              </a>
             </li>
            </ul>
           </div>
          </div>
         </div>
        </div>
       </div>
      </div>
     </nav>
     <a class="mw-logo" href="/wiki/Main_Page">
      <img alt="" aria-hidden="true" class="mw-logo-icon" height="50" src="/static/images/icons/enwiki-25.svg" width="50"/>
      <span class="mw-logo-container skin-invert">
       <img alt="Wikipedia" class="mw-logo-wordmark" src="/static/images/mobile/copyright/wikipedia-wordmark-en-25.svg" style="width: 8.75em; height: 1.375em;"/>
       <img alt="The Free Encyclopedia" class="mw-logo-tagline" height="11" src="/static/images/mobile/copyright/wikipedia-tagline-en-25.svg" style="width: 8.75em; height: 0.6875em;" width="140"/>
      </span>
     </a>
    </div>
    <div class="vector-header-end">
     <div class="vector-search-box-vue vector-search-box-collapses vector-search-box-show-thumbnail vector-search-box-auto-expand-width vector-search-box" id="p-search" role="search">
      <a accesskey="f" class="cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only search-toggle" href="/wiki/Special:Search" title="Search Wikipedia [f]">
       <span class="vector-icon mw-ui-icon-search mw-ui-icon-wikimedia-search">
       </span>
       <span>
        Search
       </span>
      </a>
      <div class="vector-typeahead-search-container">
       <div class="cdx-typeahead-search cdx-typeahead-search--show-thumbnail cdx-typeahead-search--auto-expand-width">
        <form action="/w/index.php" class="cdx-search-input cdx-search-input--has-end-button" id="searchform">
         <div class="cdx-search-input__input-wrapper" data-search-loc="header-moved" id="simpleSearch">
          <div class="cdx-text-input cdx-text-input--has-start-icon">
           <input accesskey="f" aria-label="Search Wikipedia" autocapitalize="none" autocomplete="off" class="cdx-text-input__input mw-searchInput" id="searchInput" name="search" placeholder="Search Wikipedia" spellcheck="false" title="Search Wikipedia [f]" type="search"/>
           <span class="cdx-text-input__icon cdx-text-input__start-icon">
           </span>
          </div>
          <input name="title" type="hidden" value="Special:Search"/>
         </div>
         <button class="cdx-button cdx-search-input__end-button">
          Search
         </button>
        </form>
       </div>
      </div>
     </div>
     <nav aria-label="Personal tools" class="vector-user-links vector-user-links-wide">
      <div class="vector-user-links-main">
       <div class="vector-menu mw-portlet emptyPortlet" id="p-vector-user-menu-preferences">
        <div class="vector-menu-content">
         <ul class="vector-menu-content-list">
         </ul>
        </div>
       </div>
       <div class="vector-menu mw-portlet emptyPortlet" id="p-vector-user-menu-userpage">
        <div class="vector-menu-content">
         <ul class="vector-menu-content-list">
         </ul>
        </div>
       </div>
       <nav aria-label="Appearance" class="vector-appearance-landmark">
        <div class="vector-dropdown" id="vector-appearance-dropdown" title="Change the appearance of the page's font size, width, and color">
         <input aria-haspopup="true" aria-label="Appearance" class="vector-dropdown-checkbox" data-event-name="ui.dropdown-vector-appearance-dropdown" id="vector-appearance-dropdown-checkbox" role="button" type="checkbox"/>
         <label aria-hidden="true" class="vector-dropdown-label cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only" for="vector-appearance-dropdown-checkbox" id="vector-appearance-dropdown-label">
          <span class="vector-icon mw-ui-icon-appearance mw-ui-icon-wikimedia-appearance">
          </span>
          <span class="vector-dropdown-label-text">
           Appearance
          </span>
         </label>
         <div class="vector-dropdown-content">
          <div class="vector-unpinned-container" id="vector-appearance-unpinned-container">
          </div>
         </div>
        </div>
       </nav>
       <div class="vector-menu mw-portlet emptyPortlet" id="p-vector-user-menu-notifications">
        <div class="vector-menu-content">
         <ul class="vector-menu-content-list">
         </ul>
        </div>
       </div>
       <div class="vector-menu mw-portlet" id="p-vector-user-menu-overflow">
        <div class="vector-menu-content">
         <ul class="vector-menu-content-list">
          <li class="mw-list-item user-links-collapsible-item" id="pt-sitesupport-2">
           <a class="cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet" data-mw-interface="" href="https://donate.wikimedia.org/?wmf_source=donate&amp;wmf_medium=sidebar&amp;wmf_campaign=en.wikipedia.org&amp;uselang=en">
            <span class="vector-icon mw-ui-icon-heart mw-ui-icon-wikimedia-heart">
            </span>
            <span>
             Donate
            </span>
           </a>
          </li>
          <li class="mw-list-item user-links-collapsible-item" id="pt-createaccount-2">
           <a class="" data-mw-interface="" href="/w/index.php?title=Special:CreateAccount&amp;returnto=List+of+largest+companies+in+the+Philippines" title="You are encouraged to create an account and log in; however, it is not mandatory">
            <span>
             Create account
            </span>
           </a>
          </li>
          <li class="mw-list-item user-links-collapsible-item" id="pt-login-2">
           <a accesskey="o" class="" data-mw-interface="" href="/w/index.php?title=Special:UserLogin&amp;returnto=List+of+largest+companies+in+the+Philippines" title="You're encouraged to log in; however, it's not mandatory. [o]">
            <span>

In [59]:
# Find the first table in the webpage
soup.find('table')

<table class="wikitable sortable">
<tbody><tr>
<th>Rank
</th>
<th>Name
</th>
<th>Industry
</th>
<th>Revenue<br/><small>(USD millions)</small>
</th>
<th>Profits<br/><small>(USD millions)</small>
</th>
<th>Employees
</th>
<th>Headquarters
</th></tr>
<tr>
<td>1
</td>
<td><a href="/wiki/San_Miguel_Corporation" title="San Miguel Corporation">San Miguel Corporation</a>
</td>
<td>Conglomerate
</td>
<td style="text-align:center;">26,024
</td>
<td style="text-align:center;">4
</td>
<td style="text-align:center;">53,184
</td>
<td><a href="/wiki/Mandaluyong" title="Mandaluyong">Mandaluyong</a>
</td></tr>
<tr>
<td>2
</td>
<td><a href="/wiki/SM_Investments" title="SM Investments">SM Investments</a>
</td>
<td>Conglomerate
</td>
<td style="text-align:center;">10,277
</td>
<td style="text-align:center;">1,385
</td>
<td style="text-align:center;">72,770
</td>
<td><a href="/wiki/Pasay" title="Pasay">Pasay</a>
</td></tr>
<tr>
<td>3
</td>
<td><a class="mw-redirect" href="/wiki/Manila_Electric" title="Manila Electric">Manila Electric</a>
</td>
<td>Utilities
</td>
<td style="text-align:center;">7,980
</td>
<td style="text-align:center;">684
</td>
<td style="text-align:center;">14,494
</td>
<td><a href="/wiki/Pasig" title="Pasig">Pasig</a>
</td></tr>
<tr>
<td>4
</td>
<td><a href="/wiki/JG_Summit_Holdings" title="JG Summit Holdings">JG Summit Holdings</a>
</td>
<td>Conglomerate
</td>
<td style="text-align:center;">5,932
</td>
<td style="text-align:center;">361
</td>
<td style="text-align:center;">25,979
</td>
<td>Pasig
</td></tr>
<tr>
<td>5
</td>
<td><a href="/wiki/Banco_de_Oro" title="Banco de Oro">Banco de Oro</a>
</td>
<td>Banking
</td>
<td style="text-align:center;">5,832
</td>
<td style="text-align:center;">1,321
</td>
<td style="text-align:center;">41,647
</td>
<td>Mandaluyong
</td></tr>
<tr>
<td>6
</td>
<td><a href="/wiki/Aboitiz_Equity_Ventures" title="Aboitiz Equity Ventures">Aboitiz Equity Ventures</a>
</td>
<td>Conglomerate
</td>
<td style="text-align:center;">5,588
</td>
<td style="text-align:center;">424
</td>
<td style="text-align:center;">13,802
</td>
<td><a href="/wiki/Taguig" title="Taguig">Taguig</a>
</td></tr>
<tr>
<td>7
</td>
<td><a href="/wiki/Ayala_Corporation" title="Ayala Corporation">Ayala Corporation</a>
</td>
<td>Conglomerate
</td>
<td style="text-align:center;">5,215
</td>
<td style="text-align:center;">685
</td>
<td style="text-align:center;">33,889
</td>
<td><a href="/wiki/Makati" title="Makati">Makati</a>
</td></tr>
<tr>
<td>8
</td>
<td><a href="/wiki/GT_Capital" title="GT Capital">GT Capital</a>
</td>
<td>Conglomerate
</td>
<td style="text-align:center;">5,105
</td>
<td style="text-align:center;">517
</td>
<td style="text-align:center;">39,000
</td>
<td>Makati
</td></tr>
<tr>
<td>9
</td>
<td><a class="mw-redirect" href="/wiki/Jollibee_Foods_Corporation" title="Jollibee Foods Corporation">Jollibee Foods Corporation</a>
</td>
<td>Restaurants
</td>
<td style="text-align:center;">4,391
</td>
<td style="text-align:center;">158
</td>
<td style="text-align:center;">26,263
</td>
<td>Pasig
</td></tr>
<tr>
<td>10
</td>
<td><a href="/wiki/Cosco_Capital" title="Cosco Capital">Cosco Capital</a>
</td>
<td>Conglomerate
</td>
<td style="text-align:center;">3,858
</td>
<td style="text-align:center;">133
</td>
<td style="text-align:center;">12,982
</td>
<td><a href="/wiki/Manila" title="Manila">Manila</a>
</td></tr>
<tr>
<td>11
</td>
<td><a href="/wiki/PLDT" title="PLDT">PLDT</a>
</td>
<td>Telecommunications
</td>
<td style="text-align:center;">3,795
</td>
<td style="text-align:center;">479
</td>
<td style="text-align:center;">10,004
</td>
<td>Makati
</td></tr>
<tr>
<td>12
</td>
<td><a href="/wiki/Alliance_Global" title="Alliance Global">Alliance Global</a>
</td>
<td>Conglomerate
</td>
<td style="text-align:center;">3,683
</td>
<td style="text-align:center;">352
</td>
<td style="text-align:center;">56,915
</td>
<td>Manila
</td></tr>
<tr>
<td>13
</td>
<td><a href="/wiki/Robinsons_Retail" title="Robinsons Retail">Robinsons Retail</a>
</td>
<td>Retail
</td>
<td style="text-align:center;">3,456
</td>
<td style="text-align:center;">74
</td>
<td style="text-align:center;">23,172
</td>
<td>Pasig
</td></tr>
<tr>
<td>14
</td>
<td><a class="mw-redirect" href="/wiki/Metropolitan_Bank_%26_Trust_Company" title="Metropolitan Bank &amp; Trust Company">Metropolitan Bank &amp; Trust</a>
</td>
<td>Banking
</td>
<td style="text-align:center;">3,292
</td>
<td style="text-align:center;">760
</td>
<td style="text-align:center;">18,810
</td>
<td>Makati
</td></tr>
<tr>
<td>15
</td>
<td><a href="/wiki/Globe_Telecom" title="Globe Telecom">Globe Telecom</a>
</td>
<td>Telecommunications
</td>
<td style="text-align:center;">3,241
</td>
<td style="text-align:center;">441
</td>
<td style="text-align:center;">7,542
</td>
<td>Taguig
</td></tr>
<tr>
<td>16
</td>
<td><a href="/wiki/Bank_of_the_Philippine_Islands" title="Bank of the Philippine Islands">Bank of the Philippine Islands</a>
</td>
<td>Banking
</td>
<td style="text-align:center;">3,239
</td>
<td style="text-align:center;">930
</td>
<td style="text-align:center;">19,522
</td>
<td>Makati
</td></tr>
<tr>
<td>17
</td>
<td><a href="/wiki/Philippine_Airlines" title="Philippine Airlines">PAL Holdings</a>
</td>
<td>Airline
</td>
<td style="text-align:center;">3,222
</td>
<td style="text-align:center;">302
</td>
<td style="text-align:center;">5,109
</td>
<td>Pasay
</td></tr>
<tr>
<td>18
</td>
<td><a href="/wiki/Lopez_Holdings_Corporation" title="Lopez Holdings Corporation">Lopez Holdings Corporation</a>
</td>
<td>Conglomerate
</td>
<td style="text-align:center;">2,967
</td>
<td style="text-align:center;">51
</td>
<td style="text-align:center;">11
</td>
<td>Mandaluyong
</td></tr>
<tr>
<td>19
</td>
<td><a href="/wiki/International_Container_Terminal_Services" title="International Container Terminal Services">International Container Terminal Services</a>
</td>
<td>Port management
</td>
<td style="text-align:center;">2,480
</td>
<td style="text-align:center;">512
</td>
<td style="text-align:center;">10,297
</td>
<td>Manila
</td></tr>
<tr>
<td>20
</td>
<td><a class="mw-redirect" href="/wiki/DMCI_Holdings" title="DMCI Holdings">DMCI Holdings</a>
</td>
<td>Real estate
</td>
<td style="text-align:center;">2,210
</td>
<td style="text-align:center;">445
</td>
<td style="text-align:center;">17,620
</td>
<td>Makati
</td></tr>
<tr>
<td>21
</td>
<td><a href="/wiki/LT_Group" title="LT Group">LT Group</a>
</td>
<td>Conglomerate
</td>
<td style="text-align:center;">2,074
</td>
<td style="text-align:center;">457
</td>
<td style="text-align:center;">14,296
</td>
<td>Taguig
</td></tr>
<tr>
<td>22
</td>
<td><a class="mw-redirect" href="/wiki/Unionbank_(Philippines)" title="Unionbank (Philippines)">Unionbank</a>
</td>
<td>Banking
</td>
<td style="text-align:center;">1,751
</td>
<td style="text-align:center;">163
</td>
<td style="text-align:center;">8,519
</td>
<td>Pasig
</td></tr>
<tr>
<td>23
</td>
<td><a href="/wiki/Filinvest" title="Filinvest">Filinvest</a>
</td>
<td>Real estate
</td>
<td style="text-align:center;">1,670
</td>
<td style="text-align:center;">161
</td>
<td style="text-align:center;">12,979
</td>
<td>Taguig
</td></tr>
<tr>
<td>24
</td>
<td><a href="/wiki/Rizal_Commercial_Banking_Corporation" title="Rizal Commercial Banking Corporation">Rizal Commercial Banking</a>
</td>
<td>Banking
</td>
<td style="text-align:center;">1,487
</td>
<td style="text-align:center;">220
</td>
<td style="text-align:center;">6,184
</td>
<td>Makati
</td></tr>
<tr>
<td>25
</td>
<td><a href="/wiki/Monde_Nissin" title="Monde Nissin">Monde Nissin</a>
</td>
<td>Food and beverage
</td>
<td style="text-align:center;">1,442
</td>
<td style="text-align:center;">(12)
</td>
<td style="text-align:center;">1,518
</td>
<td><a href="/wiki/Santa_Rosa,_Laguna" title="Santa Rosa, Laguna">Santa Rosa, Laguna</a>
</td></tr></tbody></table>

In [60]:
# Find a specific table with the class name "wikitable sortable"
# This helps target the exact table we want
soup.find('table', class_='wikitable sortable')

<table class="wikitable sortable">
<tbody><tr>
<th>Rank
</th>
<th>Name
</th>
<th>Industry
</th>
<th>Revenue<br/><small>(USD millions)</small>
</th>
<th>Profits<br/><small>(USD millions)</small>
</th>
<th>Employees
</th>
<th>Headquarters
</th></tr>
<tr>
<td>1
</td>
<td><a href="/wiki/San_Miguel_Corporation" title="San Miguel Corporation">San Miguel Corporation</a>
</td>
<td>Conglomerate
</td>
<td style="text-align:center;">26,024
</td>
<td style="text-align:center;">4
</td>
<td style="text-align:center;">53,184
</td>
<td><a href="/wiki/Mandaluyong" title="Mandaluyong">Mandaluyong</a>
</td></tr>
<tr>
<td>2
</td>
<td><a href="/wiki/SM_Investments" title="SM Investments">SM Investments</a>
</td>
<td>Conglomerate
</td>
<td style="text-align:center;">10,277
</td>
<td style="text-align:center;">1,385
</td>
<td style="text-align:center;">72,770
</td>
<td><a href="/wiki/Pasay" title="Pasay">Pasay</a>
</td></tr>
<tr>
<td>3
</td>
<td><a class="mw-redirect" href="/wiki/Manila_Electric" title="Manila Electric">Manila Electric</a>
</td>
<td>Utilities
</td>
<td style="text-align:center;">7,980
</td>
<td style="text-align:center;">684
</td>
<td style="text-align:center;">14,494
</td>
<td><a href="/wiki/Pasig" title="Pasig">Pasig</a>
</td></tr>
<tr>
<td>4
</td>
<td><a href="/wiki/JG_Summit_Holdings" title="JG Summit Holdings">JG Summit Holdings</a>
</td>
<td>Conglomerate
</td>
<td style="text-align:center;">5,932
</td>
<td style="text-align:center;">361
</td>
<td style="text-align:center;">25,979
</td>
<td>Pasig
</td></tr>
<tr>
<td>5
</td>
<td><a href="/wiki/Banco_de_Oro" title="Banco de Oro">Banco de Oro</a>
</td>
<td>Banking
</td>
<td style="text-align:center;">5,832
</td>
<td style="text-align:center;">1,321
</td>
<td style="text-align:center;">41,647
</td>
<td>Mandaluyong
</td></tr>
<tr>
<td>6
</td>
<td><a href="/wiki/Aboitiz_Equity_Ventures" title="Aboitiz Equity Ventures">Aboitiz Equity Ventures</a>
</td>
<td>Conglomerate
</td>
<td style="text-align:center;">5,588
</td>
<td style="text-align:center;">424
</td>
<td style="text-align:center;">13,802
</td>
<td><a href="/wiki/Taguig" title="Taguig">Taguig</a>
</td></tr>
<tr>
<td>7
</td>
<td><a href="/wiki/Ayala_Corporation" title="Ayala Corporation">Ayala Corporation</a>
</td>
<td>Conglomerate
</td>
<td style="text-align:center;">5,215
</td>
<td style="text-align:center;">685
</td>
<td style="text-align:center;">33,889
</td>
<td><a href="/wiki/Makati" title="Makati">Makati</a>
</td></tr>
<tr>
<td>8
</td>
<td><a href="/wiki/GT_Capital" title="GT Capital">GT Capital</a>
</td>
<td>Conglomerate
</td>
<td style="text-align:center;">5,105
</td>
<td style="text-align:center;">517
</td>
<td style="text-align:center;">39,000
</td>
<td>Makati
</td></tr>
<tr>
<td>9
</td>
<td><a class="mw-redirect" href="/wiki/Jollibee_Foods_Corporation" title="Jollibee Foods Corporation">Jollibee Foods Corporation</a>
</td>
<td>Restaurants
</td>
<td style="text-align:center;">4,391
</td>
<td style="text-align:center;">158
</td>
<td style="text-align:center;">26,263
</td>
<td>Pasig
</td></tr>
<tr>
<td>10
</td>
<td><a href="/wiki/Cosco_Capital" title="Cosco Capital">Cosco Capital</a>
</td>
<td>Conglomerate
</td>
<td style="text-align:center;">3,858
</td>
<td style="text-align:center;">133
</td>
<td style="text-align:center;">12,982
</td>
<td><a href="/wiki/Manila" title="Manila">Manila</a>
</td></tr>
<tr>
<td>11
</td>
<td><a href="/wiki/PLDT" title="PLDT">PLDT</a>
</td>
<td>Telecommunications
</td>
<td style="text-align:center;">3,795
</td>
<td style="text-align:center;">479
</td>
<td style="text-align:center;">10,004
</td>
<td>Makati
</td></tr>
<tr>
<td>12
</td>
<td><a href="/wiki/Alliance_Global" title="Alliance Global">Alliance Global</a>
</td>
<td>Conglomerate
</td>
<td style="text-align:center;">3,683
</td>
<td style="text-align:center;">352
</td>
<td style="text-align:center;">56,915
</td>
<td>Manila
</td></tr>
<tr>
<td>13
</td>
<td><a href="/wiki/Robinsons_Retail" title="Robinsons Retail">Robinsons Retail</a>
</td>
<td>Retail
</td>
<td style="text-align:center;">3,456
</td>
<td style="text-align:center;">74
</td>
<td style="text-align:center;">23,172
</td>
<td>Pasig
</td></tr>
<tr>
<td>14
</td>
<td><a class="mw-redirect" href="/wiki/Metropolitan_Bank_%26_Trust_Company" title="Metropolitan Bank &amp; Trust Company">Metropolitan Bank &amp; Trust</a>
</td>
<td>Banking
</td>
<td style="text-align:center;">3,292
</td>
<td style="text-align:center;">760
</td>
<td style="text-align:center;">18,810
</td>
<td>Makati
</td></tr>
<tr>
<td>15
</td>
<td><a href="/wiki/Globe_Telecom" title="Globe Telecom">Globe Telecom</a>
</td>
<td>Telecommunications
</td>
<td style="text-align:center;">3,241
</td>
<td style="text-align:center;">441
</td>
<td style="text-align:center;">7,542
</td>
<td>Taguig
</td></tr>
<tr>
<td>16
</td>
<td><a href="/wiki/Bank_of_the_Philippine_Islands" title="Bank of the Philippine Islands">Bank of the Philippine Islands</a>
</td>
<td>Banking
</td>
<td style="text-align:center;">3,239
</td>
<td style="text-align:center;">930
</td>
<td style="text-align:center;">19,522
</td>
<td>Makati
</td></tr>
<tr>
<td>17
</td>
<td><a href="/wiki/Philippine_Airlines" title="Philippine Airlines">PAL Holdings</a>
</td>
<td>Airline
</td>
<td style="text-align:center;">3,222
</td>
<td style="text-align:center;">302
</td>
<td style="text-align:center;">5,109
</td>
<td>Pasay
</td></tr>
<tr>
<td>18
</td>
<td><a href="/wiki/Lopez_Holdings_Corporation" title="Lopez Holdings Corporation">Lopez Holdings Corporation</a>
</td>
<td>Conglomerate
</td>
<td style="text-align:center;">2,967
</td>
<td style="text-align:center;">51
</td>
<td style="text-align:center;">11
</td>
<td>Mandaluyong
</td></tr>
<tr>
<td>19
</td>
<td><a href="/wiki/International_Container_Terminal_Services" title="International Container Terminal Services">International Container Terminal Services</a>
</td>
<td>Port management
</td>
<td style="text-align:center;">2,480
</td>
<td style="text-align:center;">512
</td>
<td style="text-align:center;">10,297
</td>
<td>Manila
</td></tr>
<tr>
<td>20
</td>
<td><a class="mw-redirect" href="/wiki/DMCI_Holdings" title="DMCI Holdings">DMCI Holdings</a>
</td>
<td>Real estate
</td>
<td style="text-align:center;">2,210
</td>
<td style="text-align:center;">445
</td>
<td style="text-align:center;">17,620
</td>
<td>Makati
</td></tr>
<tr>
<td>21
</td>
<td><a href="/wiki/LT_Group" title="LT Group">LT Group</a>
</td>
<td>Conglomerate
</td>
<td style="text-align:center;">2,074
</td>
<td style="text-align:center;">457
</td>
<td style="text-align:center;">14,296
</td>
<td>Taguig
</td></tr>
<tr>
<td>22
</td>
<td><a class="mw-redirect" href="/wiki/Unionbank_(Philippines)" title="Unionbank (Philippines)">Unionbank</a>
</td>
<td>Banking
</td>
<td style="text-align:center;">1,751
</td>
<td style="text-align:center;">163
</td>
<td style="text-align:center;">8,519
</td>
<td>Pasig
</td></tr>
<tr>
<td>23
</td>
<td><a href="/wiki/Filinvest" title="Filinvest">Filinvest</a>
</td>
<td>Real estate
</td>
<td style="text-align:center;">1,670
</td>
<td style="text-align:center;">161
</td>
<td style="text-align:center;">12,979
</td>
<td>Taguig
</td></tr>
<tr>
<td>24
</td>
<td><a href="/wiki/Rizal_Commercial_Banking_Corporation" title="Rizal Commercial Banking Corporation">Rizal Commercial Banking</a>
</td>
<td>Banking
</td>
<td style="text-align:center;">1,487
</td>
<td style="text-align:center;">220
</td>
<td style="text-align:center;">6,184
</td>
<td>Makati
</td></tr>
<tr>
<td>25
</td>
<td><a href="/wiki/Monde_Nissin" title="Monde Nissin">Monde Nissin</a>
</td>
<td>Food and beverage
</td>
<td style="text-align:center;">1,442
</td>
<td style="text-align:center;">(12)
</td>
<td style="text-align:center;">1,518
</td>
<td><a href="/wiki/Santa_Rosa,_Laguna" title="Santa Rosa, Laguna">Santa Rosa, Laguna</a>
</td></tr></tbody></table>

In [61]:
# Get all tables from the page and select the first one
table = soup.find_all('table')[0]

In [62]:
# Print the selected table
print(table)

<table class="wikitable sortable">
<tbody><tr>
<th>Rank
</th>
<th>Name
</th>
<th>Industry
</th>
<th>Revenue<br/><small>(USD millions)</small>
</th>
<th>Profits<br/><small>(USD millions)</small>
</th>
<th>Employees
</th>
<th>Headquarters
</th></tr>
<tr>
<td>1
</td>
<td><a href="/wiki/San_Miguel_Corporation" title="San Miguel Corporation">San Miguel Corporation</a>
</td>
<td>Conglomerate
</td>
<td style="text-align:center;">26,024
</td>
<td style="text-align:center;">4
</td>
<td style="text-align:center;">53,184
</td>
<td><a href="/wiki/Mandaluyong" title="Mandaluyong">Mandaluyong</a>
</td></tr>
<tr>
<td>2
</td>
<td><a href="/wiki/SM_Investments" title="SM Investments">SM Investments</a>
</td>
<td>Conglomerate
</td>
<td style="text-align:center;">10,277
</td>
<td style="text-align:center;">1,385
</td>
<td style="text-align:center;">72,770
</td>
<td><a href="/wiki/Pasay" title="Pasay">Pasay</a>
</td></tr>
<tr>
<td>3
</td>
<td><a class="mw-redirect" href="/wiki/Manila_Electric" title="Manila Electric">Manila Electric</a>
</td>
<td>Utilities
</td>
<td style="text-align:center;">7,980
</td>
<td style="text-align:center;">684
</td>
<td style="text-align:center;">14,494
</td>
<td><a href="/wiki/Pasig" title="Pasig">Pasig</a>
</td></tr>
<tr>
<td>4
</td>
<td><a href="/wiki/JG_Summit_Holdings" title="JG Summit Holdings">JG Summit Holdings</a>
</td>
<td>Conglomerate
</td>
<td style="text-align:center;">5,932
</td>
<td style="text-align:center;">361
</td>
<td style="text-align:center;">25,979
</td>
<td>Pasig
</td></tr>
<tr>
<td>5
</td>
<td><a href="/wiki/Banco_de_Oro" title="Banco de Oro">Banco de Oro</a>
</td>
<td>Banking
</td>
<td style="text-align:center;">5,832
</td>
<td style="text-align:center;">1,321
</td>
<td style="text-align:center;">41,647
</td>
<td>Mandaluyong
</td></tr>
<tr>
<td>6
</td>
<td><a href="/wiki/Aboitiz_Equity_Ventures" title="Aboitiz Equity Ventures">Aboitiz Equity Ventures</a>
</td>
<td>Conglomerate
</td>
<td style="text-align:center;">5,588
</td>
<td style="text-align:center;">424
</td>
<td style="text-align:center;">13,802
</td>
<td><a href="/wiki/Taguig" title="Taguig">Taguig</a>
</td></tr>
<tr>
<td>7
</td>
<td><a href="/wiki/Ayala_Corporation" title="Ayala Corporation">Ayala Corporation</a>
</td>
<td>Conglomerate
</td>
<td style="text-align:center;">5,215
</td>
<td style="text-align:center;">685
</td>
<td style="text-align:center;">33,889
</td>
<td><a href="/wiki/Makati" title="Makati">Makati</a>
</td></tr>
<tr>
<td>8
</td>
<td><a href="/wiki/GT_Capital" title="GT Capital">GT Capital</a>
</td>
<td>Conglomerate
</td>
<td style="text-align:center;">5,105
</td>
<td style="text-align:center;">517
</td>
<td style="text-align:center;">39,000
</td>
<td>Makati
</td></tr>
<tr>
<td>9
</td>
<td><a class="mw-redirect" href="/wiki/Jollibee_Foods_Corporation" title="Jollibee Foods Corporation">Jollibee Foods Corporation</a>
</td>
<td>Restaurants
</td>
<td style="text-align:center;">4,391
</td>
<td style="text-align:center;">158
</td>
<td style="text-align:center;">26,263
</td>
<td>Pasig
</td></tr>
<tr>
<td>10
</td>
<td><a href="/wiki/Cosco_Capital" title="Cosco Capital">Cosco Capital</a>
</td>
<td>Conglomerate
</td>
<td style="text-align:center;">3,858
</td>
<td style="text-align:center;">133
</td>
<td style="text-align:center;">12,982
</td>
<td><a href="/wiki/Manila" title="Manila">Manila</a>
</td></tr>
<tr>
<td>11
</td>
<td><a href="/wiki/PLDT" title="PLDT">PLDT</a>
</td>
<td>Telecommunications
</td>
<td style="text-align:center;">3,795
</td>
<td style="text-align:center;">479
</td>
<td style="text-align:center;">10,004
</td>
<td>Makati
</td></tr>
<tr>
<td>12
</td>
<td><a href="/wiki/Alliance_Global" title="Alliance Global">Alliance Global</a>
</td>
<td>Conglomerate
</td>
<td style="text-align:center;">3,683
</td>
<td style="text-align:center;">352
</td>
<td style="text-align:center;">56,915
</td>
<td>Manila
</td></tr>
<tr>
<td>13
</td>
<td><a href="/wiki/Robinsons_Retail" title="Robinsons Retail">Robinsons Retail</a>
</td>
<td>Retail
</td>
<td style="text-align:center;">3,456
</td>
<td style="text-align:center;">74
</td>
<td style="text-align:center;">23,172
</td>
<td>Pasig
</td></tr>
<tr>
<td>14
</td>
<td><a class="mw-redirect" href="/wiki/Metropolitan_Bank_%26_Trust_Company" title="Metropolitan Bank &amp; Trust Company">Metropolitan Bank &amp; Trust</a>
</td>
<td>Banking
</td>
<td style="text-align:center;">3,292
</td>
<td style="text-align:center;">760
</td>
<td style="text-align:center;">18,810
</td>
<td>Makati
</td></tr>
<tr>
<td>15
</td>
<td><a href="/wiki/Globe_Telecom" title="Globe Telecom">Globe Telecom</a>
</td>
<td>Telecommunications
</td>
<td style="text-align:center;">3,241
</td>
<td style="text-align:center;">441
</td>
<td style="text-align:center;">7,542
</td>
<td>Taguig
</td></tr>
<tr>
<td>16
</td>
<td><a href="/wiki/Bank_of_the_Philippine_Islands" title="Bank of the Philippine Islands">Bank of the Philippine Islands</a>
</td>
<td>Banking
</td>
<td style="text-align:center;">3,239
</td>
<td style="text-align:center;">930
</td>
<td style="text-align:center;">19,522
</td>
<td>Makati
</td></tr>
<tr>
<td>17
</td>
<td><a href="/wiki/Philippine_Airlines" title="Philippine Airlines">PAL Holdings</a>
</td>
<td>Airline
</td>
<td style="text-align:center;">3,222
</td>
<td style="text-align:center;">302
</td>
<td style="text-align:center;">5,109
</td>
<td>Pasay
</td></tr>
<tr>
<td>18
</td>
<td><a href="/wiki/Lopez_Holdings_Corporation" title="Lopez Holdings Corporation">Lopez Holdings Corporation</a>
</td>
<td>Conglomerate
</td>
<td style="text-align:center;">2,967
</td>
<td style="text-align:center;">51
</td>
<td style="text-align:center;">11
</td>
<td>Mandaluyong
</td></tr>
<tr>
<td>19
</td>
<td><a href="/wiki/International_Container_Terminal_Services" title="International Container Terminal Services">International Container Terminal Services</a>
</td>
<td>Port management
</td>
<td style="text-align:center;">2,480
</td>
<td style="text-align:center;">512
</td>
<td style="text-align:center;">10,297
</td>
<td>Manila
</td></tr>
<tr>
<td>20
</td>
<td><a class="mw-redirect" href="/wiki/DMCI_Holdings" title="DMCI Holdings">DMCI Holdings</a>
</td>
<td>Real estate
</td>
<td style="text-align:center;">2,210
</td>
<td style="text-align:center;">445
</td>
<td style="text-align:center;">17,620
</td>
<td>Makati
</td></tr>
<tr>
<td>21
</td>
<td><a href="/wiki/LT_Group" title="LT Group">LT Group</a>
</td>
<td>Conglomerate
</td>
<td style="text-align:center;">2,074
</td>
<td style="text-align:center;">457
</td>
<td style="text-align:center;">14,296
</td>
<td>Taguig
</td></tr>
<tr>
<td>22
</td>
<td><a class="mw-redirect" href="/wiki/Unionbank_(Philippines)" title="Unionbank (Philippines)">Unionbank</a>
</td>
<td>Banking
</td>
<td style="text-align:center;">1,751
</td>
<td style="text-align:center;">163
</td>
<td style="text-align:center;">8,519
</td>
<td>Pasig
</td></tr>
<tr>
<td>23
</td>
<td><a href="/wiki/Filinvest" title="Filinvest">Filinvest</a>
</td>
<td>Real estate
</td>
<td style="text-align:center;">1,670
</td>
<td style="text-align:center;">161
</td>
<td style="text-align:center;">12,979
</td>
<td>Taguig
</td></tr>
<tr>
<td>24
</td>
<td><a href="/wiki/Rizal_Commercial_Banking_Corporation" title="Rizal Commercial Banking Corporation">Rizal Commercial Banking</a>
</td>
<td>Banking
</td>
<td style="text-align:center;">1,487
</td>
<td style="text-align:center;">220
</td>
<td style="text-align:center;">6,184
</td>
<td>Makati
</td></tr>
<tr>
<td>25
</td>
<td><a href="/wiki/Monde_Nissin" title="Monde Nissin">Monde Nissin</a>
</td>
<td>Food and beverage
</td>
<td style="text-align:center;">1,442
</td>
<td style="text-align:center;">(12)
</td>
<td style="text-align:center;">1,518
</td>
<td><a href="/wiki/Santa_Rosa,_Laguna" title="Santa Rosa, Laguna">Santa Rosa, Laguna</a>
</td></tr></tbody></table>

In [63]:
# Find all table header cells (<th>)
# These are usually the column names
ph_company_titles = table.find_all('th')

In [64]:
# Print all headers
print(ph_company_titles)

[<th>Rank
</th>, <th>Name
</th>, <th>Industry
</th>, <th>Revenue<br/><small>(USD millions)</small>
</th>, <th>Profits<br/><small>(USD millions)</small>
</th>, <th>Employees
</th>, <th>Headquarters
</th>]

In [65]:
# Clean the text inside each header
# strip() removes extra spaces and line breaks
ph_table_titles =[title.text.strip() for title in ph_company_titles]

In [67]:
# Print cleaned column names
print(ph_table_titles)

['Rank', 'Name', 'Industry', 'Revenue(USD millions)', 'Profits(USD millions)', 'Employees', 'Headquarters']

In [68]:
# Check the data type
type(ph_table_titles)

list

In [69]:
# Import pandas for handling tabular data
import pandas as pd

In [70]:
# Create an empty DataFrame using the scraped column names
df = pd.DataFrame(columns = ph_table_titles)
# Display empty DataFrame
df

Empty DataFrame
Columns: [Rank, Name, Industry, Revenue(USD millions), Profits(USD millions), Employees, Headquarters]
Index: []

In [71]:
# Find all rows inside the table
column_data = table.find_all('tr')

In [73]:
# Loop through each row except the header row
for row in column_data[1:]:
    # Find all table data cells (<td>) inside the row
    row_data = row.find_all('td')
    # Clean each cell value using strip()
    individual_row_data =[data.text.strip() for data in row_data]
    # Get current length of DataFrame
    # This will be used as the new row index
    length = len(df)
    # Insert scraped row data into the DataFrame
    df.loc[length]= individual_row_data

In [51]:
# Display the completed DataFrame
df

,Rank,Name,Industry,Revenue(USD millions),Profits(USD millions),Employees,Headquarters
0,1,San Miguel Corporation,Conglomerate,"26,024",4,"53,184",Mandaluyong
1,2,SM Investments,Conglomerate,"10,277","1,385","72,770",Pasay
2,3,Manila Electric,Utilities,"7,980",684,"14,494",Pasig
3,4,JG Summit Holdings,Conglomerate,"5,932",361,"25,979",Pasig
4,5,Banco de Oro,Banking,"5,832","1,321","41,647",Mandaluyong
5,6,Aboitiz Equity Ventures,Conglomerate,"5,588",424,"13,802",Taguig
6,7,Ayala Corporation,Conglomerate,"5,215",685,"33,889",Makati
7,8,GT Capital,Conglomerate,"5,105",517,"39,000",Makati
8,9,Jollibee Foods Corporation,Restaurants,"4,391",158,"26,263",Pasig
9,10,Cosco Capital,Conglomerate,"3,858",133,"12,982",Manila
10,11,PLDT,Telecommunications,"3,795",479,"10,004",Makati
11,12,Alliance Global,Conglomerate,"3,683",352,"56,915",Manila
12,13,Robinsons Retail,Retail,"3,456",74,"23,172",Pasig
13,14,Metropolitan Bank & Trust,Banking,"3,292",760,"18,810",Makati
14,15,Globe Telecom,Telecommunications,"3,241",441,"7,542",Taguig
15,16,Bank of the Philippine Islands,Banking,"3,239",930,"19,522",Makati
16,17,PAL Holdings,Airline,"3,222",302,"5,109",Pasay
17,18,Lopez Holdings Corporation,Conglomerate,"2,967",51,11,Mandaluyong
18,19,International Container Terminal Services,Port management,"2,480",512,"10,297",Manila
19,20,DMCI Holdings,Real estate,"2,210",445,"17,620",Makati
20,21,LT Group,Conglomerate,"2,074",457,"14,296",Taguig
21,22,Unionbank,Banking,"1,751",163,"8,519",Pasig
22,23,Filinvest,Real estate,"1,670",161,"12,979",Taguig
23,24,Rizal Commercial Banking,Banking,"1,487",220,"6,184",Makati
24,25,Monde Nissin,Food and beverage,"1,442",(12),"1,518","Santa Rosa, Laguna"
25,1,San Miguel Corporation,Conglomerate,"26,024",4,"53,184",Mandaluyong
26,2,SM Investments,Conglomerate,"10,277","1,385","72,770",Pasay
27,3,Manila Electric,Utilities,"7,980",684,"14,494",Pasig
28,4,JG Summit Holdings,Conglomerate,"5,932",361,"25,979",Pasig
29,5,Banco de Oro,Banking,"5,832","1,321","41,647",Mandaluyong
30,6,Aboitiz Equity Ventures,Conglomerate,"5,588",424,"13,802",Taguig
31,7,Ayala Corporation,Conglomerate,"5,215",685,"33,889",Makati
32,8,GT Capital,Conglomerate,"5,105",517,"39,000",Makati
33,9,Jollibee Foods Corporation,Restaurants,"4,391",158,"26,263",Pasig
34,10,Cosco Capital,Conglomerate,"3,858",133,"12,982",Manila
35,11,PLDT,Telecommunications,"3,795",479,"10,004",Makati
36,12,Alliance Global,Conglomerate,"3,683",352,"56,915",Manila
37,13,Robinsons Retail,Retail,"3,456",74,"23,172",Pasig
38,14,Metropolitan Bank & Trust,Banking,"3,292",760,"18,810",Makati
39,15,Globe Telecom,Telecommunications,"3,241",441,"7,542",Taguig
40,16,Bank of the Philippine Islands,Banking,"3,239",930,"19,522",Makati
41,17,PAL Holdings,Airline,"3,222",302,"5,109",Pasay
42,18,Lopez Holdings Corporation,Conglomerate,"2,967",51,11,Mandaluyong
43,19,International Container Terminal Services,Port management,"2,480",512,"10,297",Manila
44,20,DMCI Holdings,Real estate,"2,210",445,"17,620",Makati
45,21,LT Group,Conglomerate,"2,074",457,"14,296",Taguig
46,22,Unionbank,Banking,"1,751",163,"8,519",Pasig
47,23,Filinvest,Real estate,"1,670",161,"12,979",Taguig
48,24,Rizal Commercial Banking,Banking,"1,487",220,"6,184",Makati
49,25,Monde Nissin,Food and beverage,"1,442",(12),"1,518","Santa Rosa, Laguna"

In [74]:
# Export the DataFrame into a CSV file
# index=False removes the default index column in the CSV
df.to_csv(r'C:\Users\PC\Desktop\Data Analytics\Python\Outputs_here\Top_Company_PH.csv', index = False)